# meant to be applied using
# kubectl --namespace kafka patch deployment confluent-oss-cp-kafka-rest --patch "$(cat 04-patch-confluent-kafka-rest.yml )"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-oss-cp-kafka-rest
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: cp-kafka-rest-server
        env:
        - name: KAFKAREST_OPTS
          valueFrom:
            configMapKeyRef:
              name: confluent-kafka-rest-opts-configmap
              key: kafka_rest_kafkarest_opts
        volumeMounts:
        - name: jolokia-jar
          mountPath: "/opt/jolokia"
      - name: telegraf
        image: docker.io/telegraf:latest
        resources:
          requests:
            cpu: 10m
            memory: 60Mi
          limits:
            memory: 120Mi
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: env
        - name: LABEL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: label
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPLUNK_HEC_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: splunk_hec_url
        - name: SPLUNK_HEC_TOKEN
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: splunk_hec_token
        volumeMounts:
        - name: telegraf-config-confluent-kafka-rest
          mountPath: /etc/telegraf
      volumes:
      - name: confluent-kafka-rest-opts-configmap
        configMap:
          name: confluent-kafka-rest-opts-configmap
      - name: telegraf-config-confluent-kafka-rest
        configMap:
          name: telegraf-config-confluent-kafka-rest
      - name: jolokia-jar
        configMap:
          name: jolokia-jar
