# Section: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-monitor
  namespace: kafka
  labels:
    k8s-app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-monitor
  template:
    metadata:
      labels:
        name: kafka-monitor
    spec:
      containers:
      - name: kafka-monitor
        image: guilhemmarchand/kafka-monitor:latest
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 500Mi
        #command:
        #- "/opt/kafka-monitor/bin/kafka-monitor-start.sh /usr/local/share/kafka-monitor/kafka-monitor.properties"
        volumeMounts:
        - name: kafka-monitor-config
          mountPath: /opt/kafka-monitor/config
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kafka-monitor-config
        configMap:
          name: kafka-monitor-config
