kind: ConfigMap
metadata:
  name: telegraf-config-kafka-monitor
  namespace: kafka
apiVersion: v1
data:

  telegraf.conf: |+
    [global_tags]
      env = "$ENV"
    [agent]
      hostname = "$POD_NAME"
    [[outputs.http]]
      ## URL is the address to send metrics to
      url = "https://ec2-18-130-146-104.eu-west-2.compute.amazonaws.com:8088/services/collector"
      ## Use TLS but skip chain & host verification
      insecure_skip_verify = true
      data_format = "splunkmetric"
      splunkmetric_hec_routing = true
      ## Additional HTTP headers
      [outputs.http.headers]
        Content-Type = "application/json"
        Authorization = "Splunk 205d43f1-2a31-4e60-a8b3-327eda49944a"
        X-Splunk-Request-Channel = "205d43f1-2a31-4e60-a8b3-327eda49944a"

    # Kafka-connect JVM monitoring

    [[inputs.jolokia2_agent]]
      name_prefix = "kafka_"
      urls = ["http://$POD_NAME:8778/jolokia"]

    [[inputs.jolokia2_agent.metric]]
      name         = "kafka-monitor"
      mbean        = "kmf.services:name=*,type=*"
