# meant to be applied using
# kubectl --namespace kafka patch deployment confluent-oss-cp-schema-registry --patch "$(cat 04-patch-confluent-schema-registry.yml )"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-oss-cp-schema-registry
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: cp-schema-registry-server
        env:
        - name: SCHEMA_REGISTRY_OPTS
          valueFrom:
            configMapKeyRef:
              name: confluent-schema-registry-opts-configmap
              key: schema_registry_opts
        volumeMounts:
        - name: jolokia-jar
          mountPath: "/opt/jolokia"
      - name: telegraf
        image: docker.io/telegraf:latest
        resources:
          requests:
            cpu: 10m
            memory: 60Mi
          limits:
            memory: 120Mi
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: env
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPLUNK_HEC_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: splunk_hec_url
        - name: SPLUNK_HEC_TOKEN
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: splunk_hec_token
        volumeMounts:
        - name: telegraf-config-confluent-schema-registry
          mountPath: /etc/telegraf
      volumes:
      - name: confluent-schema-registry-opts-configmap
        configMap:
          name: confluent-schema-registry-opts-configmap
      - name: telegraf-config-confluent-schema-registry
        configMap:
          name: telegraf-config-confluent-schema-registry
      - name: jolokia-jar
        configMap:
          name: jolokia-jar
