kind: ConfigMap
metadata:
  name: telegraf-config-kafka-connect
  namespace: kafka
apiVersion: v1
data:

  telegraf.conf: |+
    [global_tags]
      env = "$ENV"
      label = "$LABEL"
    [agent]
      hostname = "$POD_NAME"
    [[outputs.http]]
      url = "https://$SPLUNK_HEC_URL/services/collector"
      insecure_skip_verify = true
      data_format = "splunkmetric"
      splunkmetric_hec_routing = true
      [outputs.http.headers]
        Content-Type = "application/json"
        Authorization = "Splunk $SPLUNK_HEC_TOKEN"
        X-Splunk-Request-Channel = "$SPLUNK_HEC_TOKEN"

    # Kafka-connect JVM monitoring

    [[inputs.jolokia2_agent]]
      name_prefix = "kafka_connect."
      urls = ["http://$POD_NAME:8778/jolokia"]

    [[inputs.jolokia2_agent.metric]]
      name         = "worker"
      mbean        = "kafka.connect:type=connect-worker-metrics"

    [[inputs.jolokia2_agent.metric]]
      name         = "worker"
      mbean        = "kafka.connect:type=connect-worker-rebalance-metrics"

    [[inputs.jolokia2_agent.metric]]
      name         = "connector-task"
      mbean        = "kafka.connect:type=connector-task-metrics,connector=*,task=*"
      tag_keys = ["connector", "task"]

    [[inputs.jolokia2_agent.metric]]
      name         = "sink-task"
      mbean        = "kafka.connect:type=sink-task-metrics,connector=*,task=*"
      tag_keys = ["connector", "task"]

    [[inputs.jolokia2_agent.metric]]
      name         = "source-task"
      mbean        = "kafka.connect:type=source-task-metrics,connector=*,task=*"
      tag_keys = ["connector", "task"]

    [[inputs.jolokia2_agent.metric]]
      name         = "error-task"
      mbean        = "kafka.connect:type=task-error-metrics,connector=*,task=*"
      tag_keys = ["connector", "task"]

    # Kafka connect return a status value which is non numerical
    # Using the enum processor with the following configuration replaces the string value by our mapping
    [[processors.enum]]
      [[processors.enum.mapping]]
        ## Name of the field to map
        field = "status"

        ## Table of mappings
        [processors.enum.mapping.value_mappings]
          paused = 0
          running = 1
          unassigned = 2
          failed = 3
          destroyed = 4
