# meant to be applied using
# kubectl --namespace kafka patch deployment confluent-oss-cp-kafka-connect --patch "$(cat 04-patch-shared-volume-and-splunk-uf.yml )"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-oss-cp-kafka-connect
  namespace: kafka
spec:
  template:
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: kafka-connect-log4j-configmap
        configMap:
          name: kafka-connect-log4j-configmap
      containers:
      - name: cp-kafka-connect-server
        env:
        - name: KAFKA_LOG4J_OPTS
          value: "-Dlog4j.configuration=file:/usr/local/share/kafka/log4j.properties"
        - name: LOG_DIR
          value: "/var/log/kafka"
        volumeMounts:
        - name: kafka-connect-log4j-configmap
          mountPath: "/usr/local/share/kafka"
        - name: shared-data
          mountPath: "/var/log/kafka"
      - name: splunk
        image: splunk/universalforwarder:latest
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license"
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: global-splunk-uf-secrets
              key: splunk_password
        - name: SPLUNK_DEPLOYMENT_SERVER
          valueFrom:
            configMapKeyRef:
              name: global-splunk-uf-config
              key: splunk_deployment_server
        - name: SPLUNK_S2S_PORT
          valueFrom:
            configMapKeyRef:
              name: global-splunk-uf-config
              key: splunk_s2s_port
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            memory: 256Mi
        volumeMounts:
        - name: shared-data
          mountPath: "/var/log/kafka"
