kind: ConfigMap
metadata:
  name: kafka-brokers-splunk-inputs
  namespace: kafka
apiVersion: v1
data:

  inputs.conf: |+

    [monitor:///var/log/kafka/controller.log]
    disabled = false
    index = kafka
    sourcetype = kafka:broker:controller

    [monitor:///var/log/kafka/server.log]
    disabled = false
    index = kafka
    sourcetype = kafka:broker:server

    [monitor:///var/log/kafka/state-change.log]
    disabled = false
    index = kafka
    sourcetype = kafka:broker:state-change

    [monitor:///var/log/kafka/log-cleaner.log]
    disabled = false
    index = kafka
    sourcetype = kafka:broker:log-cleaner

    [monitor:///var/log/kafka/kafka-request.log]
    disabled = false
    index = kafka
    sourcetype = kafka:broker:kafka-request

    [monitor:///var/log/kafka/kafka-authorizer.log]
    disabled = fale
    index = kafka
    sourcetype = kafka:broker:kafka-authorizer

    [monitor:///var/log/kafka/*-gc.log*.current]
    disabled = fale
    index = kafka
    sourcetype = kafka:broker:gc-log

  props.conf: |+

    [kafka:broker:controller]
    EVENT_BREAKER_ENABLE=true
    EVENT_BREAKER=([\n\r]+)\[\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\,\d{3}\]

    [kafka:broker:server]
    EVENT_BREAKER_ENABLE=true
    EVENT_BREAKER=([\n\r]+)\[\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\,\d{3}\]

    [kafka:broker:state-change]
    EVENT_BREAKER_ENABLE=true
    EVENT_BREAKER=([\n\r]+)\[\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\,\d{3}\]

    [kafka:broker:log-cleaner]
    EVENT_BREAKER_ENABLE=true
    EVENT_BREAKER=([\n\r]+)\[\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\,\d{3}\]

    [kafka:broker:kafka-request]
    EVENT_BREAKER_ENABLE=true
    EVENT_BREAKER=([\n\r]+)\[\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\,\d{3}\]

    [kafka:broker:kafka-authorizer]
    EVENT_BREAKER_ENABLE=true
    EVENT_BREAKER=([\n\r]+)\[\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\,\d{3}\]
