# meant to be applied using
# kubectl --namespace kafka patch statefulset confluent-oss-cp-kafka --patch "$(cat 03-patch-shared-volume-and-splunk-uf.yml )"
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: confluent-oss-cp-kafka
  namespace: kafka
spec:
  template:
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: kafka-brokers-log4j-configmap
        configMap:
          name: kafka-brokers-log4j-configmap
      - name: kafka-brokers-splunk-inputs
        configMap:
          name: kafka-brokers-splunk-inputs
      containers:
      - name: cp-kafka-broker
        env:
        - name: KAFKA_OPTS
          valueFrom:
            configMapKeyRef:
              name: kafka-brokers-opts-configmap
              key: kafka_brokers_kafka_opts
        volumeMounts:
        - name: kafka-brokers-log4j-configmap
          mountPath: "/usr/local/share/kafka"
        - name: shared-data
          mountPath: "/var/log/kafka"
      - name: splunk
        image: splunk/universalforwarder:latest
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license"
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: global-splunk-uf-secrets
              key: splunk_password
        - name: SPLUNK_DEPLOYMENT_SERVER
          valueFrom:
            configMapKeyRef:
              name: global-splunk-uf-config
              key: splunk_deployment_server
        - name: SPLUNK_S2S_PORT
          valueFrom:
            configMapKeyRef:
              name: global-splunk-uf-config
              key: splunk_s2s_port
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            memory: 256Mi
        volumeMounts:
        - name: shared-data
          mountPath: "/var/log/kafka"
        - name: kafka-brokers-splunk-inputs
          mountPath: "/opt/splunkforwarder/etc/apps/TA-kafka-brokers/local"
