kind: ConfigMap
metadata:
  name: telegraf-config-confluent-ksql-server
  namespace: kafka
apiVersion: v1
data:

  telegraf.conf: |+
    [global_tags]
      env = "$ENV"
      label = "$LABEL"
    [agent]
      hostname = "$POD_NAME"
    [[outputs.http]]
      url = "https://$SPLUNK_HEC_URL/services/collector"
      insecure_skip_verify = true
      data_format = "splunkmetric"
      splunkmetric_hec_routing = true
      [outputs.http.headers]
        Content-Type = "application/json"
        Authorization = "Splunk $SPLUNK_HEC_TOKEN"
        X-Splunk-Request-Channel = "$SPLUNK_HEC_TOKEN"

    # ksql-server JVM monitoring

    [[inputs.jolokia2_agent]]
      name_prefix = "kafka_"
      urls = ["http://$POD_NAME:8778/jolokia"]

    [[inputs.jolokia2_agent.metric]]
      name         = "ksql-server"
      mbean        = "io.confluent.ksql.metrics:type=*"
      paths = ["error-rate", "num-persistent-queries", "messages-consumed-per-sec", "messages-produced-per-sec", "num-active-queries" , "num-idle-queries", "messages-consumed-max"]
